version: 2.1

executors:
  builder_new:
    machine:
      image: ubuntu-2204:2023.10.1
  builder_old:
    machine:
      image: ubuntu-2204:2023.04.2  # https://circleci.com/docs/configuration-reference/#available-linux-machine-images-cloud

commands:
  build_and_test:
    steps:
      - checkout
      - run:
          name: Install test tools
          command: |
            sudo apt update -qq
            sudo apt install -y -qq moreutils
            npm install --global --silent --no-progress tap-xunit bats
      - run:
          name: Test
          command: |
            mkdir ~/reports
            bats --print-output-on-failure test.bats | pee cat "tap-xunit > ~/reports/result.xml"
      - store_test_results:
          path: ~/reports

jobs:
  build_new:
    executor: builder_new
    steps:
      - build_and_test
  build_old:
    executor: builder_old
    steps:
      - build_and_test

workflows:
  debug_build:
    jobs:
      - build_new
      - build_old
